// <auto-generated />
using System;
using AgroSolutions.ProcessamentoDados.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroSolutions.ProcessamentoDados.Migrations
{
    [DbContext(typeof(ProcessamentoDbContext))]
    partial class ProcessamentoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroSolutions.ProcessamentoDados.Domain.Entities.AgregacaoDados", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DesvioPadrao")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LeiturasInvalidas")
                        .HasColumnType("int");

                    b.Property<int>("LeiturasNormais")
                        .HasColumnType("int");

                    b.Property<int>("LeiturasSuspeitas")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodoFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodoInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TalhaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoAgregacao")
                        .HasColumnType("int");

                    b.Property<int>("TipoSensor")
                        .HasColumnType("int");

                    b.Property<int>("TotalLeituras")
                        .HasColumnType("int");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("ValorMaximo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ValorMedio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ValorMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("PeriodoInicio");

                    b.HasIndex("PropriedadeId");

                    b.HasIndex("SensorId");

                    b.HasIndex("TalhaoId");

                    b.HasIndex("TipoAgregacao");

                    b.HasIndex("SensorId", "TipoAgregacao", "PeriodoInicio")
                        .IsUnique();

                    b.ToTable("AgregacoesDados", (string)null);
                });

            modelBuilder.Entity("AgroSolutions.ProcessamentoDados.Domain.Entities.LeituraProcessada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DadosAdicionais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IntensidadeSinal")
                        .HasColumnType("int");

                    b.Property<Guid>("LeituraOrigemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("NivelBateria")
                        .HasColumnType("int");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Qualidade")
                        .HasColumnType("int");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TalhaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampLeitura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimestampProcessamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimestampRecebimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoSensor")
                        .HasColumnType("int");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LeituraOrigemId");

                    b.HasIndex("PropriedadeId");

                    b.HasIndex("SensorId");

                    b.HasIndex("Status");

                    b.HasIndex("TalhaoId");

                    b.HasIndex("TimestampLeitura");

                    b.HasIndex("SensorId", "TimestampLeitura");

                    b.ToTable("LeiturasProcessadas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
