@AgroSolutions.Propriedades_HostAddress = http://localhost:5260

GET {{AgroSolutions.Propriedades_HostAddress}}/todos/
Accept: application/json

###

GET {{AgroSolutions.Propriedades_HostAddress}}/todos/1
Accept: application/json

###
