apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: agrosolutions
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: agrosolutions-k8s
        environment: development
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'identidade'
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s
        static_configs:
          - targets: ['identidade-service:8080']
            labels:
              service: 'identidade'
      
      - job_name: 'propriedades'
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s
        static_configs:
          - targets: ['propriedades-service:8080']
            labels:
              service: 'propriedades'
      
      - job_name: 'ingestaodados'
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s
        static_configs:
          - targets: ['ingestaodados-service:8080']
            labels:
              service: 'ingestaodados'
      
      - job_name: 'processamentodados'
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s
        static_configs:
          - targets: ['processamentodados-service:8080']
            labels:
              service: 'processamentodados'
      
      - job_name: 'analise'
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s
        static_configs:
          - targets: ['analise-service:8080']
            labels:
              service: 'analise'
      
      - job_name: 'notificacoes'
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s
        static_configs:
          - targets: ['notificacoes-service:8080']
            labels:
              service: 'notificacoes'
      
      - job_name: 'sensores'
        metrics_path: '/metrics'
        scrape_interval: 10s
        scrape_timeout: 5s
        static_configs:
          - targets: ['sensores-service:8080']
            labels:
              service: 'sensores'
