// <auto-generated />
using System;
using AgroSolutions.IngestaoDados.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgroSolutions.IngestaoDados.Migrations
{
    [DbContext(typeof(IngestaoDbContext))]
    partial class IngestaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgroSolutions.IngestaoDados.Domain.Entities.LeituraSensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DadosAdicionais")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("IntensidadeSinal")
                        .HasColumnType("int");

                    b.Property<int?>("NivelBateria")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Qualidade")
                        .HasColumnType("int");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimestampLeitura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimestampRecebimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Qualidade")
                        .HasDatabaseName("IX_Leituras_Qualidade");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("IX_Leituras_SensorId");

                    b.HasIndex("TimestampLeitura")
                        .HasDatabaseName("IX_Leituras_TimestampLeitura");

                    b.HasIndex("SensorId", "TimestampLeitura")
                        .HasDatabaseName("IX_Leituras_SensorId_TimestampLeitura");

                    b.ToTable("Leituras", (string)null);
                });

            modelBuilder.Entity("AgroSolutions.IngestaoDados.Domain.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Altitude")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IntervaloLeituraMinutos")
                        .HasColumnType("int");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PropriedadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TalhaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaCalibracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UltimaLeitura")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("IX_Sensores_DeviceId");

                    b.HasIndex("PropriedadeId")
                        .HasDatabaseName("IX_Sensores_PropriedadeId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Sensores_Status");

                    b.HasIndex("TalhaoId")
                        .HasDatabaseName("IX_Sensores_TalhaoId");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("IX_Sensores_Tipo");

                    b.ToTable("Sensores", (string)null);
                });

            modelBuilder.Entity("AgroSolutions.IngestaoDados.Domain.Entities.LeituraSensor", b =>
                {
                    b.HasOne("AgroSolutions.IngestaoDados.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Leituras")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("AgroSolutions.IngestaoDados.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
