apiVersion: v1
kind: ConfigMap
metadata:
  name: agrosolutions-config
  namespace: agrosolutions
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__RequireHttpsMetadata: "false"
